### ISSUE TITLE
How do I write a username or a specific date on Archivate?

### ISSUE THREAD

**Issue by naziko2411** [naer2/instagramStoryDownloader#8]

**Comment by naer2** [comment]
Maybe @afwn90cj93201nixr2e1re help you about this.

**Comment by afwn90cj93201nixr2e1re** [comment]
```bash
#!/usr/bin/env bash
working_dir="downloaded";

#writing dates into file
rm -rf ./test.txt
find ./$working_dir -daystart -maxdepth 1 -type f ! -mtime -2 -exec stat -c "%y" {} \; | awk '{ print $1; }' | sort -u > test.txt

#enable webdav server
screen -S wd3 -d -m -c /dev/null -- sh -c 'dotnet /root/mono/wdmrc.dll -p 8888; exec $SHELL'
sleep 5s
while read -r line; do
    # Do what you want to $name
	start_date="${line} 00:00:00";
	end_date="${line} 23:59:59";
	archive_title=`date --date ${line} +"%d-%m-%Y"`;
	password="archive_password___${archive_title}";
	if find ./$working_dir -type f \( -iname '*.jpg' -o -iname '*.mp4' \) -newermt "$start_date" -not -newermt "$end_date" -printf "./$working_dir/%f\n" | rar a -m5 -ma5 -mt4 -o+ -ow -hp"$password" -qo- -t -tk -tl -tsmca -u -y -df -- $archive_title.rar @ 2>&1 > /dev/null;then
		echo "everything is fine $archive_title" | tee -a done.txt;
		if curl --fail-early --anyauth --user "xxxxxxx@xxxx.xxxx:xxxxxxpasswordxxxx" -T "$archive_title.rar" "http://127.0.0.1:8888/somedir/" 2>&1 > /dev/null;then
			echo "uploaded $archive_title.rar" | tee -a done.txt;
			rm ./$archive_title.rar
		#	mv $archive_title.rar uploaded/$archive_title.rar
		else
			echo "Falied to upload $archive_title.rar" | tee -a undone.txt;
		fi;
	else
		echo "something not nice $archive_title" | tee -a undone.txt;
	fi;
	echo "end of checking $archive_title";
done < "test.txt"

#disable webdav server
screen -X -S wd3 kill
```


Rn im using (since 27.03.2020) this to archivate and upload files to cloud, be careful, make backups before running script.
![изображение](https://user-images.githubusercontent.com/9306996/85948505-d02ee080-b940-11ea-940b-1171171350b0.png)
![изображение](https://user-images.githubusercontent.com/9306996/85948515-de7cfc80-b940-11ea-92e1-86b716a9e3e4.png)
![изображение](https://user-images.githubusercontent.com/9306996/85948528-eb015500-b940-11ea-8aed-46ac7bb4cd5b.png)
![изображение](https://user-images.githubusercontent.com/9306996/85948539-f8b6da80-b940-11ea-98e7-e3127daf3186.png)
![изображение](https://user-images.githubusercontent.com/9306996/85948551-04a29c80-b941-11ea-850d-6d8525918ab0.png)

Also there is my crontab configuration:
![изображение](https://user-images.githubusercontent.com/9306996/85948581-3ddb0c80-b941-11ea-993a-956892ead494.png)


@naziko2411  can u provide more information with examples of what u need, coz i really dont get what u mean under 'username', ur's username? Or what? what a specific date do u need?

**Comment by naziko2411** [comment]
Like 2018, 2019 such as serenayss, enisarikan, ezomola, etc.

**Comment by afwn90cj93201nixr2e1re** [comment]
Bro, give an example
what should be inside 2018?
What should be inside 2019?
What should be inside serenayss?

You should edit Archivate.sh or script which posted in previous comment.
Scripts are not part of main script, it's just addition, there's no way to make it general-purpose.
